###############
# User Inputs #
###############

alias: unknown # default: unknown
batch_size: 512 # default: 512
cfg_negative_prompt:
cfg_scale: 1,000000 # default: 1.0
chunks: -1 # default: -1 (unlimited)
color: false # default: false
ctx_size: 512 # default: 512
escape: false # default: false
export: false # default: false
file: # never logged, see prompt instead. Can still be specified for input.
frequency_penalty: 0,000000 # default: 0.0 
grammar:
grammar-file: # never logged, see grammar instead. Can still be specified for input.
hellaswag: false # default: false
hellaswag_tasks: 400 # default: 400
ignore_eos: false # default: false
in_prefix:
in_prefix_bos: false # default: false
in_suffix:
instruct: false # default: false
interactive: false # default: false
interactive_first: false # default: false
keep: 0 # default: 0
logdir: ./ # default: unset (no logging)
logit_bias:
lora: 
lora_base: 
low_vram: false # default: false
main_gpu: 0 # default: 0
memory_f32: false # default: false
mirostat: 0 # default: 0 (disabled)
mirostat_ent: 5,000000 # default: 5.0
mirostat_lr: 0,100000 # default: 0.1
mlock: false # default: false
model: ./models/7B/ggml-model-q4_0.gguf # default: models/7B/ggml-model.bin
model_draft:  # default:
multiline_input: false # default: false
n_gpu_layers: -1 # default: -1
n_predict: 10 # default: -1 (unlimited)
n_probs: 0 # only used by server binary, default: 0
no_mmap: false # default: false
no_mul_mat_q: false # default: false
no_penalize_nl: false # default: false
numa: false # default: false
ppl_output_type: 0 # default: 0
ppl_stride: 0 # default: 0
presence_penalty: 0,000000 # default: 0.0
prompt:
prompt_cache: 
prompt_cache_all: false # default: false
prompt_cache_ro: false # default: false
prompt_tokens:
random_prompt: false # default: false
repeat_penalty: 1,100000 # default: 1.1
reverse_prompt:
rope_freq_base: 10000,000000 # default: 10000.0
rope_freq_scale: 1,000000 # default: 1.0
seed: 1695554224 # default: -1 (random seed)
simple_io: false # default: false
temp: 0,800000 # default: 0.8
tensor_split: [0,000000e+00]
tfs: 1,000000 # default: 1.0
threads: 4 # default: 4
top_k: 40 # default: 40
top_p: 0,950000 # default: 0.95
typical_p: 1,000000 # default: 1.0
verbose_prompt: false # default: false
